version: "3.7"
services:
  production:
    build:
      context: ./docker
      dockerfile: server.Dockerfile
    env_file:
      - ./.env
    environment:
      - NODE_ENV=dev
      - docker_host=db
    volumes:
      - ./:/app
    command: npm run dev

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}

  adminer:
    image: adminer
    restart: always
    ports:
      - 2000:8080
